### ISSUE TITLE
CU Boulder Arts & Sciences Impact Status Reports 

### ISSUE THREAD

**Issue by ktheiler** [CUCentralAdvancement/eComm#20]
CU Boulder's A&S Advancement team would like to send out donor impact reports in the fall on behalf of approx. 25 departments through 25 emails (requiring 25 list builds). We'd like to streamline this project because this level of support is out of scope and not advisable for many reasons (more lists/more emails increases risk for errors).

**Acceptance Criteria**

- [ ] Create a process that streamlines this effort into one email list with dynamic tags or content blocks and one email template.
- [ ] Help A&S prioritize departments (in our experience, A&S can make a large effort to send out information to under 10 donors)

**Comment by alexfinnarn** [comment]
using Thankview and do not need support from Digital Marketing
